"""add Department

Revision ID: 038f9ee6e40a
Revises: 5a02a0f04129
Create Date: 2025-01-10 15:47:16.151863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '038f9ee6e40a'
down_revision = '5a02a0f04129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
