"""rename department

Revision ID: 5465aca1f8d2
Revises: 038f9ee6e40a
Create Date: 2025-01-10 15:54:36.001113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5465aca1f8d2'
down_revision = '038f9ee6e40a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
